apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form
  template:
    metadata:
      labels:
        app: form
    spec:
      containers:
      - name: form
        image: localhost:8087/form:1.0
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: form-service
spec:
  selector:
    app: form
  type: NodePort
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
    nodePort: 31111
