apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form
  template:
    metadata:
      labels:
        app: form
    spec:
      containers:
      - name: form
        image: localhost:8087/form:1.0
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  selector:
    app: form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
